### ISSUE TITLE
Optimizar tiempo de carga de textos en .csv

### ISSUE THREAD

**Issue by vikyale** [ElotlMX/Esquite#125]
Al realizar cargas de .csv con más de 100K de registros, el tiempo de carga supera a más de 3 horas desde el servidor Elasticsearch local.

Una posible solución sería mejorar la carga por batches.
https://elasticsearch-py.readthedocs.io/en/v8.1.3/helpers.html

**Comment by umoqnier** [comment]
Me parece excelente idea, trabajo en ello :100:

**Comment by umoqnier** [comment]
Closed on #127
