### ISSUE TITLE
Codigo de conducta

### ISSUE THREAD

**Issue by umoqnier** [ElotlMX/Esquite#62]
Escribir un código de conducta para habilitar espacios incluyentes. @penserbjorne recomienda https://www.contributor-covenant.org/. ¿Traducir al español? ¿Traducir a otro idioma? @ximenina @jusafing

**Comment by penserbjorne** [comment]
Hola!

A mi me parece adecuado el covenant, considero que tiene los lineamientos adecuados, y ya ha sido adoptado y probado por equipos de proyectos más grandes.

En cuanto al idioma, creo que es algo que tenemos que definiri en general para los proyectos. Yo veria adecuado dejar todo en ingles, y posteriormente incorporar alguna herramienta de localización.
