### ISSUE TITLE
Allow flexible  fields in the CSV

### ISSUE THREAD

**Issue by ximenina** [ElotlMX/Esquite#74]
Currently, Esquite parse the following fields: L1, L2, dialect, source. We would like to allow more fields in case the user has more annotated data.

(Spanish)
Actualmente Esquite parsea los siguientes campos obligatorios:  L1, L2, dialecto, fuente. Nos gustaría permitir más campos dinámicos, dependiendo de los datos  que tenga cada usuario.

**Comment by umoqnier** [comment]
Closed in 0cf41e6
